services:

  fastapi:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000"
    depends_on:
      - qdrant
      - ollama
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}

  flask:
    build:
      context: .
      dockerfile: ingestion/Dockerfile
    ports:
      - "5000"
    depends_on:
      - qdrant
      - ollama

  streamlit:
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "8501"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.streamlit.rule=PathPrefix(`/`)"
      - "traefik.http.services.streamlit.loadbalancer.server.port=8501"
    depends_on:
      - traefik

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333"
    volumes:
      - qdrant_data:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    ports:
      - "11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: /bin/sh
    command: -c "ollama serve & sleep 5 && ollama pull qwen3-embedding:0.6b && wait"

  traefik:
    image: traefik:v3.0
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  qdrant_data:
  ollama_data: